
export const colors = {
  black: '#000112',
  veryDarkGrey: '#20212C',
  darkGrey: '#2B2C37',
  linesDark: '#3E3F4E',
  mediumGrey: '#828FA3',
  linesLight: '#E4EBFA',
  lightGrey: '#F4F7FD',
  white: '#FFFFFF',
  mainPurple: '#635FC7',
  mainPurpleHover: '#A8A4FF',
  red: '#EA5555',
  redHover: '#FF9898',
  pallette: {
    berryRed: { name: 'Berry Red', value: '#b8256f' },
    red: { name: 'Red', value: '#db4035' },
    orange: { name: 'Orange', value: '#ff9933' },
    yellow: { name: 'Yellow', value: '#fad000' },
    oliveGreen: { name: 'Olive Green', value: '#afb83b' },
    limeGreen: { name: 'Lime Green', value: '#7ecc49' },
    green: { name: 'Green', value: '#299438' },
    mintGreen: { name: 'Mint Green', value: '#6accbc' },
    teal: { name: 'Teal', value: '#158fad' },
    skyBlue: { name: 'Sky Blue', value: '#14aaf5' },
    lightBlue: { name: 'Light Blue', value: '#96c3eb' },
    blue: { name: 'Blue', value: '#4073ff' },
    grape: { name: 'Grape', value: '#884dff' },
    violet: { name: 'Violet', value: '#af38eb' },
    lavender: { name: 'Lavender', value: '#eb96eb' },
    magenta: { name: 'Magenta', value: '#e05194' },
    salmon: { name: 'Salmon', value: '#ff8d85' },
    charcoal: { name: 'Charcoal', value: '#808080' },
    grey: { name: 'Grey', value: '#b8b8b8' },
    taupe: { name: 'Taupe', value: '#ccac93' },
  }
}
